### ISSUE TITLE
indentkeys doesn't work

### ISSUE THREAD

**Issue by wlnirvana** [Shougo/neocomplete.vim#483] opened 2015-10-09 10:50 UTC
Exactly same problem for c++ described [here](https://github.com/Shougo/neocomplete.vim/issues/311#issuecomment-62594330) appear again. Current neocomplete version d2a78075207b97c105041927a125e2cf0b2b0ca5

**Last updated (OCT 18 2015)**:
I think this might be a conflict of `Vundle` and `neocomplete`. Below is relevant info.

```sh
lw715@vm-shell4:~$ uname -a
Linux vm-shell4.doc.ic.ac.uk 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
lw715@vm-shell4:~$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
...(omitted)
```

.vimrc:
```.vimrc
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Shougo/neocomplete.vim'

call vundle#end()            " required
filetype plugin indent on    " required


let g:neocomplete#enable_at_startup = 1
```

problematic c++ program:
```c++
int main()
{
    float a = int('a');
    switch (a) {
        case 1:
                case 2:
                case 4:
                case 3:
    }
    return 0;
}
```

screenshot:
![out](https://github-cloud.s3.amazonaws.com/assets/3822785/10565598/61e3c9f4-75cc-11e5-8e74-30404d894991.gif)

And this problem also happens on another machine of mine with the follow versions:
```sh
benben@localhost:~$ uname -a
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt17-1 (2015-09-26) x86_64 GNU/Linux
benben@localhost:~$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:35:48)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
...(omitted)
```

**Comment by Shougo** [comment] 2015-10-10 01:27
I cannot reproduce it.
Please read the issue template.

https://github.com/Shougo/neocomplete.vim/issues/236

Closing until you have read it.

**Comment by wlnirvana** [comment] 2015-10-15 22:33
@Shougo See update above

**Comment by Shougo** [comment] 2015-10-17 03:01
I have tested it.  But I cannot reproduce it.

Please upload the reproduce ways instead of just upload sample code.
You should update your Vim to latest version.   Your version information(just 7.4) is very poor.

**Comment by wlnirvana** [comment] 2015-10-18 18:22
@Shougo it's actually quite easy to reproduce the problem on my machines: just enter the code mentioned. I attached a screenshot and updated detailed version info above.

**Comment by Shougo** [comment] 2015-10-20 11:43
Fixed.

**Closed** 2015-10-20 11:43 UTC

**Comment by wlnirvana** [comment] 2015-10-20 16:25
Great! Thanks a lot.
