### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [Shougo/neocomplete.vim#566] opened 2016-12-12 23:17 UTC
# Problems summary
The first item in the candidates completion window is selected even after I use
`let g:neocomplete#enable_auto_select=0`

## Expected
No item in the candidate window to be selected until I begin scroling

## Environment Information
 * OS: 10.12.1
 * Vim version: 8.0.14

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#auto_complete_delay = 25
let g:neocomplete#auto_completion_start_length = 0
let g:neocomplete#enable_auto_select = 0
let g:neocomplete#max_list = 50

" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
`
```

## The reproduce ways from Vim starting (Required!)

 1. opening vim
 2. going to a code file (I use java)
 3. typing a word in the file
 4. Candidate box pops up and first is selected

## Screen shot (if possible)
![neocomplete_issue_2016-12-12 18 14 12](https://cloud.githubusercontent.com/assets/9679243/21120783/0dc15b04-c097-11e6-86bf-283abdba1b96.png)

## Upload the log messages by `:redir` and `:message`
No weird messages.

**Comment by Shougo** [comment] 2016-12-12 23:50
Your minimal .vimrc is not minimal.
It cannot be executed by `vim -u minimal.vim`.

Please upload the real minimal vimrc.
Please see other issues.

**Comment by Shougo** [comment] 2016-12-12 23:51
I think other plugin or configuration changes `completeopt` value.
You should check it.

**Comment by Luis-Henriquez-Perez** [comment] 2016-12-13 00:12
I attach the real vim minimal here. I will read the other issues and check the completeopt value and see if I can find the answer there.

[minimal.vim.zip](https://github.com/Shougo/neocomplete.vim/files/647611/minimal.vim.zip)

**Comment by Luis-Henriquez-Perez** [comment] 2016-12-13 00:26
After opening vim the completeopt was the default value: menu,preview.

**Comment by Shougo** [comment] 2016-12-13 06:32
> minimal.vim.zip

I have downloaded it.
But it includes only generic configurations.
It does not include the plugin configurations.
It cannot load plugin.
So I cannot test the behavior.

**Comment by Shougo** [comment] 2016-12-13 06:37
This is the real minimal vimrc.
It is the minimal.

Your minimal configuration includes non related changes.

**Comment by Luis-Henriquez-Perez** [comment] 2016-12-13 07:21
[plugins.vim.zip](https://github.com/Shougo/neocomplete.vim/files/648202/plugins.vim.zip)

**Comment by Shougo** [comment] 2016-12-13 07:28
Please upload the code in the issue...
I don't want to unzip it.

**Comment by Shougo** [comment] 2016-12-13 07:29
I have downloaded it.

```vim
function! Cond(cond, ...)
	let opts = get(a:000, 0, {})
	return a:cond ? opts : extend(opts, {'on': [], 'for': []})
endfunction

call plug#begin('~/.config/nvim/plugged')
Plug 'itchyny/lightline.vim'
Plug 'chriskempson/base16-vim'
Plug 'godlygeek/tabular'
Plug 'rhysd/vim-clang-format'
Plug 'airblade/vim-gitgutter'
Plug 'yggdroot/indentline'
Plug 'majutsushi/tagbar'
Plug 'ludovicchabant/vim-gutentags'
Plug 'Shougo/deoplete.nvim',
    \Cond(has('nvim'),
    \{ 'do': 'UpdateRemotePlugins' })
Plug 'shougo/neocomplete.vim',
    \Cond(!has('nvim'))
Plug 'jiangmiao/auto-pairs'
Plug 'konfekt/fastfold'
Plug 'sirver/ultisnips'
Plug 'honza/vim-snippets'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-surround'
Plug 'benekastah/neomake'
Plug 'mbbill/undotree'
Plug 'ntpeters/vim-better-whitespace'
Plug 'mileszs/ack.vim'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf'
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()
```

It is quite too long.
And did you test it?

I think you don't understand the minimal vimrc and the reproduce ways.
Please read other issues (again).

**Comment by Shougo** [comment] 2016-12-13 07:30
I will close the issue if you don't tell me the information.

**Comment by Luis-Henriquez-Perez** [comment] 2016-12-13 07:33
You're right I don't think I understand. I'm sorry. You can close the issue.

**Comment by Shougo** [comment] 2016-12-13 07:40
You should create the minimal vimrc.
Because, I think some plugin or configuration brokes your `completeopt`.
It may be neocomplete or other plugin.
Your minimal vimrc is quite long.  So I cannot check the plugins or configurations.

If you cannot, unfortunately I will close the issue.

**Comment by Luis-Henriquez-Perez** [comment] 2016-12-13 08:10
I figured it out. I had duplicate settings for neocompete that kept overriding my settings.

**Comment by Shougo** [comment] 2016-12-13 08:14
OK.  It seems solved.
I will close it.

**Closed by Shougo** 2016-12-13 08:14 UTC
Labels: cannot reproduce, reproduce ways
