### ISSUE TITLE
A very weird popup menu problem in MacVim 8.0.32

### ISSUE THREAD

**Issue by markwu** [Shougo/neocomplete.vim#560] opened 2016-10-17 13:25 UTC
# Problems summary
The popup menu does not popup until I moved the mouse in GUI MacVim (mvim). But it works very well under terminal MacVim (vim)

I can't tell the problem is caused by NeoComplete, PhpComplete or MacVim it self.

## Expected
Popup menu works both GUI and Terminal MacVim

## Environment Information
 * OS: OSX 10.11.6
 * Vim version: 8.0.32 (MacVim)

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set nocompatible
filetype off

set rtp+=~/Projects/vim-test/bundle/neobundle.vim/

call neobundle#begin(expand('~/Projects/vim-test/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim', {
    \ 'build' : {
    \     'windows' : 'make -f make_mingw32.mak',
    \     'cygwin' : 'make -f make_cygwin.mak',
    \     'mac' : 'make -f make_mac.mak',
    \     'unix' : 'make -f make_unix.mak',
    \    },
    \ }

" Put your bundle here
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'shawncplus/phpcomplete.vim'

call neobundle#end()

filetype plugin indent on

NeoBundleCheck

" Put your plugin settings here

syntax on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" neocomplete.vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Shortcut for toggle neocomplete
noremap <Leader>no :NeoCompleteToggle<CR>

" Use neocomplete
let g:neocomplete#enable_at_startup = 1

" Use smartcase
let g:neocomplete#enable_smart_case = 1

" Set minimum syntax keyword length
let g:neocomplete#sources#syntax#min_keyword_length = 3

" Define dictionary
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : ''
    \ }

call neocomplete#custom#source('_', 'sorters', [])

" Define keyword
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" SuperTab like snippets behavior
imap <expr><TAB> pumvisible() ? "\<C-N>" : "\<TAB>"
smap <expr><TAB> pumvisible() ? "\<C-N>" : "\<TAB>"
imap <expr><S-TAB> pumvisible() ? "\<C-P>" : "\<S-TAB>"
smap <expr><S-TAB> pumvisible() ? "\<C-P>" : "\<S-TAB>"

" <CR>: close popup and save indent
inoremap <silent> <CR> <C-R>=<SID>ClosePopup()<CR>
function! <SID>ClosePopup()
    return pumvisible() ? "\<C-Y>" : "\<CR>"
endfunction

" Undo and manual completion
inoremap <expr><C-G> neocomplete#undo_completion()
inoremap <expr><C-L> neocomplete#complete_common_string()

" Enable heavy omni completion
if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
let g:neocomplete#sources#omni#input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
let g:neocomplete#sources#omni#input_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
let g:neocomplete#sources#omni#input_patterns.perl = '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif

" Enable tags completion
" let g:neocomplete#sources#tags#cache_limit_size = 20000000

" Manual omni completion
inoremap <expr><C-F> neocomplete#start_manual_complete()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" phpcomplete.vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:phpcomplete_relax_static_constraint = 1

```

## The reproduce ways from Vim starting (Required!)

1. Edit test.php
2. Type the following code

```php
<?php
    $date = new Date();  // Popup will show here
    $date-> // Popup will not show here, until you moved the mouse corsor
```

## Screen shot (if possible)
![Screencast](https://cloud.githubusercontent.com/assets/196861/19439231/f36718a6-94af-11e6-8837-fff6bb99d5bc.gif)

## Upload the log messages by `:redir` and `:message`
Nope

**Comment by markwu** [comment] 2016-10-17 13:57
A more clear screencast to show the problem:

![untitled](https://cloud.githubusercontent.com/assets/196861/19440383/4b503378-94b4-11e6-8c2d-db0fdbf205da.gif)

You can see the first case, the popup menu only shows when I move the mouse cursor. And, in second case, the popup menu only show when I press any key that match the candidates.

Hope this screencast describe my problem clear.

**Comment by Shougo** [comment] 2016-10-17 15:22
I will close it.  Because, at least it is not neocomplete problem.
I think it just cached...
You should create new issue in phpcomplete.vim in first.

**Comment by markwu** [comment] 2016-10-17 16:14
After some tests, I think it is neocomplete's problem, the problem occurs after this commit https://github.com/Shougo/neocomplete.vim/commit/1b99b4c43ddf70cd0a2008425f8920f8113e4cbb .

Before this commit, everything works well.

**Comment by Shougo** [comment] 2016-10-17 16:38
Really?  It is timer bug in Vim?
OK.  I will test it.

**Comment by markwu** [comment] 2016-10-17 16:40
I am not sure if vim timer cause this problem, but after I checkout  this commit b00675d2a698e34d4ff1e9ac61227fac69d776b8, everything just works.

**Comment by Shougo** [comment] 2016-10-17 16:41
The commit uses timer feature in Vim.
So, if it does not work, it is timer bug.

**Comment by Shougo** [comment] 2016-10-18 15:17
I cannot reproduce the problem in GVim...
You can disable the feature by `g:neocomplete#auto_complete_delay`.

**Closed by Shougo** 2016-10-18 15:17 UTC

**Comment by markwu** [comment] 2016-10-18 15:52
Okay, The problem disappeared after I set `g:neocomplete#auto_complete_delay` to 0. Thanks.

**Comment by Shougo** [comment] 2016-11-07 22:30
This feature is disabled in MacVim.
It seems broken.

**Comment by markwu** [comment] 2016-11-08 00:15
Ah ... Thanks for your investigation, should I report this to MacVim, or it already a known issue?

**Comment by gotgenes** [comment] 2016-11-08 06:07
I didn't notice this issue. I filed essentially a duplicate of this, #563. You can see the resolution in 	fdf3883 was to not use timers for MacVim.

**Comment by markwu** [comment] 2016-11-08 09:11
@gotgenes Great thanks, you just save my time.
