### ISSUE TITLE
cannot input characters after enable_refresh_always = 1 ?

### ISSUE THREAD

**Issue by VinaLx** [Shougo/neocomplete.vim#576] opened 2017-03-16 14:46 UTC
# Problems summary

I got a strange behavior of the completion after `let g:enable_refresh_always = 1`.
Sometimes after popup menu appears, following input only cause the menu to blink but actual characters never show up.

## Environment Information

VIM - Vi IMproved 8.0
MacOS X (unix) version

## vimrc

```vim
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_refresh_always = 1
```

## The reproduce ways from Vim starting

In file test.cpp ( this problem doesn't seem to appear in plain text )
```
test
test
```
when I try to type the `test` in the second line, following characters (`s` and `t`) are stuck ( so are every other characters except for backspace ), and there is a single entry in the popup menu (`test [B]`).

What's going on and do I miss something?
I'm also using YouCompleteMe at the same time, with custom options disabled, does ycm somehow affect the behavior of neo? 

Thanks !

**Comment by Shougo** [comment] 2017-03-21 07:13
Please provide the minimal configuration.

I will close the issue if it is not provided.

> I'm also using YouCompleteMe at the same time, with custom options disabled, does ycm somehow affect the behavior of neo?

I think it is the plugin conflicts with neocomplete and YouCompleteMe.
You should not mix them.

**Comment by Shougo** [comment] 2017-03-21 07:15
I cannot reproduce the problem.  Because you don't provide the minimal vimrc information.
We have not ESP skills.

> I'm also using YouCompleteMe at the same time, with custom options disabled, does ycm somehow affect the behavior of neo?

The vimrc does not include any of YouCompleteMe configuration.

**Comment by VinaLx** [comment] 2017-03-21 09:38
I use the default config of YCM, and the minimum vimrc is essentially enable YCM and neocomplete at the same time:
```vim

" vundle setup
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'shougo/neocomplete.vim'

call vundle#end()            " required
filetype plugin indent on    " required

" neocomplete
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_refresh_always = 1
```

Maybe I just shouldn't mix them together ?

**Comment by Shougo** [comment] 2017-03-21 09:39
> Maybe I just shouldn't mix them together ?

Yes, it will conflict.
It is out of support.

**Closed** 2017-03-21 09:39 UTC
Labels: cannot reproduce, reproduce ways
