### ISSUE TITLE
Dictionary source not working

### ISSUE THREAD

**Issue by petobens** [Shougo/neocomplete.vim#428] opened 2015-07-03 14:42 UTC
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/neocomplete/
set runtimepath+=$DOTVIM/bundle/vimshell/
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#sources#dictionary#dictionaries = {
        \ 'default' : '',
        \ 'vimshell' : $DOTVIM.'/ftplugin/vimshell/vimshell_dictionary.dict'
        \ }
```

Where the file `vimshell_dictionary.dict` only contains the word `atest`.

Now open Gvim and run `:VimShell`, then type `ate`. I expect neocomplete to complete `atest` from the dictionary source but nothing happens:

![foo](https://cloud.githubusercontent.com/assets/2583971/8501063/62631a72-2178-11e5-8492-f8be512d7ef3.gif)

**Comment by Shougo** [comment] 2015-07-04 09:57
I cannot reproduce it.
I think your dictionary file is not cached.
It is slower in Windows env.
You should execute `NeoCompleteDictionaryMakeCache` command.

**Comment by petobens** [comment] 2015-07-05 14:34
With the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/neocomplete/
set runtimepath+=$DOTVIM/bundle/vimshell/
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.vimshell = ['dictionary']
let g:neocomplete#sources#dictionary#dictionaries = {
        \ 'default' : '',
        \ 'vimshell' : $DOTVIM.'/ftplugin/vimshell/vimshell_dictionary.dict'
        \ }
```
If I open GVim and run `:VimShell`, then in my `.cache` directory two folders are created: `neocomplete/dictionary_cache` and `neocomplete/keyword_patterns`. The `dictionary_cache` folder contains the file `C=-=+OD=+Users=+Pedro=+vimfiles=+ftplugin=+vimshell=+vimshell_dictionary.dict` which consists of

```
{'atest'}
```

The `keyword_patterns` folder also contains a file name `C=-=+OD=+Users=+Pedro=+vimfiles=+ftplugin=+vimshell=+vimshell_dictionary.dict` but this file now consists of:

```
\$\$\?\w*\|[[:alpha:]_.\\/~-][[:alnum:]_.\\/~-]*\|\d\+\%(\.\d\+\)\+
```

So I think the dictionary file is indeed cached properly.  However if I type `ate` there is no completion from the dictionary source:

![foo](https://cloud.githubusercontent.com/assets/2583971/8512058/b4579406-2309-11e5-9883-7899f67c044b.gif)

**Comment by Shougo** [comment] 2015-07-11 04:29
OK.  It is problem.
But it works for me.
Please debug dictionary source.
I cannot reproduce it.

**Comment by petobens** [comment] 2015-07-11 15:07
Thank Shougo. I will try to see what's going on. I'm sure this used to work before but I cannot seem to find the source of the problem. Have you changed the dictionary source recently?

**Comment by petobens** [comment] 2015-07-11 23:37
Can you try this in a Windows computer? There are good and updated Windows builds [here](https://tuxproject.de/projects/vim/).

**Comment by Shougo** [comment] 2015-07-12 05:17
> Thank Shougo. I will try to see what's going on. I'm sure this used to work before but I cannot seem to find the source of the problem. How am i supposed to debug the dictionary source?

Please see dictionary.vim

```vim
function! s:source.gather_candidates(context) "{{{
  let list = []

  for ft in neocomplete#get_source_filetypes(
        \ neocomplete#get_context_filetype())
    if !has_key(s:dictionary_cache, ft)
      call s:make_cache(ft)
    endif
    call neocomplete#cache#check_cache(
          \ 'dictionary_cache', ft,
          \ s:async_dictionary_list, s:dictionary_cache, 1)

    let list += get(s:dictionary_cache, ft, [])
  endfor

  return list
endfunction"}}}
```

I think the problem is exists in `neocomplete#cache#check_cache()`.
It loads candidates dictionary from cache.

**Comment by Shougo** [comment] 2015-07-12 05:18
> Thank Shougo. I will try to see what's going on. I'm sure this used to work before but I cannot seem to find the source of the problem. How am i supposed to debug the dictionary source?

You can use `git bisect`.

**Comment by petobens** [comment] 2015-07-18 19:49
I can't find the root of the problem. Please whenever you can, try testing this yourself in a Windows machine. Thank you!

**Comment by Shougo** [comment] 2015-07-19 01:48
No.  I don't want to  test it in Windows.

**Comment by Shougo** [comment] 2015-07-19 07:38
I tested your dictionary in Windows environement(This is special).
It works for me.
Closing.

**Closed by Shougo** 2015-07-19 07:38 UTC
Labels: wontfix, Works for me

**Comment by petobens** [comment] 2015-07-24 15:17
Hi @Shougo thank you for testing on Windows. What version/build did you use? Did you try it exactly with my minimal vimrc? I cannot get this to work on my machine and it is something I really use on daily basis so I need this to work again. Thanks!

**Comment by Shougo** [comment] 2015-07-24 15:19
It may path problem.
Please change the vimshell dictionary path.

**Comment by Shougo** [comment] 2015-07-24 15:22
I tired and I have not much time to debug your environment.
You should debug it.

**Comment by Shougo** [comment] 2015-07-24 15:34
> Hi @Shougo thank you for testing on Windows. What version/build did you use? Did you try it exactly with my minimal vimrc? I cannot get this to work on my machine and it is something I really use on daily basis so I need this to work again. Thanks!

Please don't use HOME directory files dictionary to test the problem.
Why?   I have not your HOME directory.
You should more simple path for example "C:"/vimshell_dictionary.dict".
I can test it.

**Comment by petobens** [comment] 2015-08-12 00:18
Hi @Shougo, I finally had time to look a bit into this (sorry for the late  reply). Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/neocomplete/
set runtimepath+=$DOTVIM/bundle/vimshell/
set runtimepath+=$DOTVIM/bundle/vimproc/
filetype plugin indent on

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#sources')
    let g:neocomplete#sources = {}
endif
let g:neocomplete#sources.vimshell = ['dictionary']
let g:neocomplete#sources#dictionary#dictionaries = {
        \ 'default' : '',
        \ 'vimshell' : 'C:/OD/vimshell.dict',
        \ }

" Mapping to test gather candidates
nnoremap ,lc :call <SID>source_gather_candidates()<CR>

" FROM HERE ON WE COPY PART OF `dictionary.vim` SOURCE:
let s:source = {'name' : 'dictionary'}

if !exists('s:dictionary_cache')
    let s:dictionary_cache = {}
    let s:async_dictionary_list = {}
endif

function! s:source_gather_candidates() "{{{
  let list = []

  for ft in neocomplete#get_source_filetypes(
        \ neocomplete#get_context_filetype())
    if !has_key(s:dictionary_cache, ft)
      call s:make_cache(ft)
    endif
    echo s:async_dictionary_list
    call neocomplete#cache#check_cache(
          \ 'dictionary_cache', ft,
          \ s:async_dictionary_list, s:dictionary_cache, 1)
    echo s:dictionary_cache

    " let list += get(s:dictionary_cache, ft, [])
  endfor
  " return list
endfunction"}}}

function! s:make_cache(filetype) "{{{
  if !has_key(s:dictionary_cache, a:filetype)
        \ && !has_key(s:async_dictionary_list, a:filetype)
    call neocomplete#sources#dictionary#remake_cache(a:filetype)
  endif
endfunction"}}}

function! neocomplete#sources#dictionary#remake_cache(filetype) "{{{
  if !neocomplete#is_enabled()
    call neocomplete#initialize()
  endif

  let filetype = a:filetype
  if filetype == ''
    let filetype = neocomplete#get_context_filetype(1)
  endif

  if !has_key(s:async_dictionary_list, filetype)
    let s:async_dictionary_list[filetype] = []
  endif

  let pattern = neocomplete#get_keyword_pattern(filetype, s:source.name)
  for dictionary in neocomplete#sources#dictionary#get_dictionaries(filetype)
    let dictionary = neocomplete#util#substitute_path_separator(
          \ fnamemodify(dictionary, ':p'))
    if filereadable(dictionary)
      call neocomplete#print_debug('Make cache dictionary: ' . dictionary)
      call add(s:async_dictionary_list[filetype], {
            \ 'filename' : dictionary,
            \ 'cachename' : neocomplete#cache#async_load_from_file(
            \       'dictionary_cache', dictionary, pattern, 'D')
            \ })
    endif
  endfor
endfunction"}}}

```

where I copied the three relevant functions from `dictionary.vim.` source. 

Now open Gvim, run `:VimShell`, exit insert mode and call the `source_gather_candidates()` function with the `lc` mapping. I get as an output:

![blah](https://cloud.githubusercontent.com/assets/2583971/9213901/f88b73b4-406d-11e5-97c5-aa764dd51440.gif)


As you told me, the problem effectively seems to be with `neocomplete#cache#check_cache()` (since `s:dictionary_cache` value is empty: `{'vimshell' : []}`). 

Therefore I think the problem might be `neocomplete#cache#load_from_cache()` function, but I have no idea how to debug further.
Any kind of help will be greatly appreciated. Thanks in advance!

**Comment by petobens** [comment] 2015-08-12 04:19
If I write the `s:source_gather_candidates()` function like this:

```vim
function! s:source_gather_candidates() "{{{
  let list = []

  for ft in neocomplete#get_source_filetypes(
        \ neocomplete#get_context_filetype())
    if !has_key(s:dictionary_cache, ft)
      call s:make_cache(ft)
    endif

    " THIS IS THE NEW PART
    let s:VCache = neocomplete#util#get_vital().import('System.Cache')
    echo s:async_dictionary_list[ft]
    let cache_dir = neocomplete#get_data_directory() . '/' . 'dictionary_cache'
    let cache_file = filter(copy(s:async_dictionary_list[ft]), 'filereadable(v:val.cachename)')[0].filename
    echo s:VCache.readfile(cache_dir, cache_file)
    echo get(s:VCache.readfile(cache_dir, cache_file), 0, '[]')

    call neocomplete#cache#check_cache(
          \ 'dictionary_cache', ft,
          \ s:async_dictionary_list, s:dictionary_cache, 1)

    let list += get(s:dictionary_cache, ft, [])
  endfor

  return list
endfunction"}}}
```

and repeat the procedure above then I get:

![screenshot-12-08-2015_01-17-50](https://cloud.githubusercontent.com/assets/2583971/9216467/fa355758-408f-11e5-9cbf-ec2ad1e27fd4.png)

Maybe this helps (I find it strange that `echo get(s:VCache.readfile(cache_dir, cache_file), 0, '[]')` returns a set `{'atest', 'ipconfig'}` rather than a list.

**Comment by Shougo** [comment] 2015-08-12 08:05
> Maybe this helps. Personally I find it strange that echo get(s:VCache.readfile(cache_dir, cache_file), 0, '[]') returns a set {'atest', 'ipconfig'} rather than a list ['atest', 'ipconfig']. But really I have no idea where the problem is.

It is correct.  Because, your source loading routine is wrong.
Please see `neocomplete#cache#load_from_cache()`.
It converts Lua's list to VimL list.

**Comment by petobens** [comment] 2015-08-12 15:01
Hi @Shougo. I test with the Lua part of `neocomplete#cache#load_from_cache()` and found out that the problem is with `loadstring()`. I'm using Lua 5.3 and and `loadstring` was deprecated in favor of `load` in  Lua 5.2.

**Comment by Shougo** [comment] 2015-08-13 01:28
Thanks.  But I must reject your PR.
Because, your changes does not support Lua 5.1 behavior.
I will fix it.

**Comment by Shougo** [comment] 2015-08-13 01:34
Fixed.  Please test it.

**Comment by petobens** [comment] 2015-08-13 02:24
Thank you! It is working great now. Sorry that my PR was not backward compatible.
