### ISSUE TITLE
insert all function prototype

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/neocomplete.vim#461] opened 2015-08-16 10:39 UTC
@Shougo  when neocomplete make a sugestion and you choose it insert object.function( it's not nice it will be cool if it insert all the prototype object.function(param1 ,param2); and make the param1 in visual mode and when you tape tabe it move to the next it will be much fuster . i now snippet do that but it will be nicer if neocomplete do that . if neocomplete do that it will be the best because in my opinion it the only big issues believe me it will be nuch faster.

**Comment by 7belrhalmia** [comment] 2015-08-16 10:40
@Shougo like that neocomplete insert object.function(int a ,String Z) and all int a is in visual mode when you type tab it move to String Z this will be amazing

**Comment by Shougo** [comment] 2015-08-18 11:21
No.  It is not auto completion's work.
Closing.

**Closed by Shougo** 2015-08-18 11:21 UTC

**Comment by Shougo** [comment] 2015-08-21 21:41
@7belrhalmia I implemented the feature in neosnippet.
After you completed items, neosnippet creates snippet item automatically.

**Comment by 7belrhalmia** [comment] 2015-08-22 21:52
@Shougo  thanks man you are the best

**Comment by 7belrhalmia** [comment] 2015-08-22 21:55
@Shougo  hwo we can trrigers the snippet automatcly with out pressing tab , like when we select the function it autotrigger the snippet with out pressing tab

**Comment by Shougo** [comment] 2015-08-22 22:19
You can define the mapping like this.

```vim
imap <expr><silent>L     neocomplete#mappings#close_popup() .
      \ "\<Plug>(neosnippet_jump_or_expand)"
```

**Comment by 7belrhalmia** [comment] 2015-08-22 22:29
@Shougo  that's work  , but there is one last problem is i changed L key to <cr> key so by pressing enter neosnnipet expand , but by doing that enter in insert mode don't do a return line

**Comment by 7belrhalmia** [comment] 2015-08-22 22:33
also with tab if we mapped tab , tab key will not work

**Comment by Shougo** [comment] 2015-08-22 22:36
@7belrhalmia You should study Vim key mappings feature, and change the mapping.
It is out of my support range.

**Comment by 7belrhalmia** [comment] 2015-08-23 19:56
@Shougo  i work on it last night i do like this : 
imap <expr> <silent> <cr> neosnippet#expandable_or_jumpable() ?
            \ "<Plug>(neosnippet_expand_or_jump)" :
            \ neocomplete#mappings#close_popup()."\<CR>"

**Comment by 7belrhalmia** [comment] 2015-08-23 19:59
there is one problem if the function has no paramettre it insert two ()  in the and  like the image bellow  file.stat ()(): 

![screenshot from 2015-08-23 20 45 44](https://cloud.githubusercontent.com/assets/13202562/9429941/a4f7c4a8-49d9-11e5-80f0-ec88c2480a16.png)

**Comment by Shougo** [comment] 2015-08-24 23:19
Fixed.  Please update neosnippet.

**Comment by 7belrhalmia** [comment] 2015-08-25 00:18
@Shougo    this mapping work fine for me : 

     imap < expr> < silent> < cr> pumvisible() ?
    \ neocomplete#mappings#close_popup() . "<Plug>(neosnippet_jump_or_expand)" :
    \ "<CR>"


except there is one problem  : for the first time when i autocomplete a function it's grate like println 

![screenshot from 2015-08-25 01 14 18](https://cloud.githubusercontent.com/assets/13202562/9455795/e0a2d9c8-4ac6-11e5-8c1b-6885bbf15824.png)

but in the second time when i wont to autocomplete a function  that's not work it jump to the last < '0' > like this 
![screenshot from 2015-08-25 01 14 49](https://cloud.githubusercontent.com/assets/13202562/9455818/26384de2-4ac7-11e5-83ec-cfc84e331241.png)

**Comment by Shougo** [comment] 2015-08-25 10:47
You should use `"\<Plug>(neosnippet_expand_or_jump)" ` instead of `"\<Plug>(neosnippet_jump_or_expand)" .`

**Comment by 7belrhalmia** [comment] 2015-08-25 16:47
@Shougo  that's resolve  the half of the problem (i shoud think of that solution )   but it still another problem.   there is the other problem : 

if i expand functions thats work fine and evrythings is ok  but when i expand fields  it return to the last placeholder
![screenshot from 2015-08-25 17 46 42](https://cloud.githubusercontent.com/assets/13202562/9473167/47893fe4-4b51-11e5-8e61-4f3d52c77248.png)   so in this examplewhen i expand state it return to the last placeholder

**Comment by Shougo** [comment] 2015-08-25 22:46
> if i expand functions thats work fine and evrythings is ok but when i expand fields it return to the last placeholder

It is feature.
Because, the fields are not snippet trigger.

**Comment by 7belrhalmia** [comment] 2015-08-25 22:53
yah @Shougo  i understand thanks

**Comment by svanharmelen** [comment] 2015-08-29 19:29
@7belrhalmia so I'm trying to set this up as well... But using:

```
imap <expr> <CR> pumvisible() ?
    \ deoplete#mappings#close_popup() . "\<Plug>(neosnippet_expand_or_jump)" :
    \ "\<CR>"
```

Results in getting this:

![image](https://cloud.githubusercontent.com/assets/4171547/9563921/cdbfcf24-4e94-11e5-9a4e-ad96ac94a1a1.png)

If I change only `<CR>` for `L`, it works correctly using `L`... So what am I doing wrong? @Shougo could you confirm this isn't a deoplete specific problem? As the exact same thing seems to work with neocomplete.

(using nvim btw)

**Comment by 7belrhalmia** [comment] 2015-08-29 21:19
@svanharmelen  this map i use :

imap <expr> <silent> <cr> pumvisible() ?
    \ neocomplete#mappings#close_popup() . "\<Plug>(neosnippet_expand_or_jump)" :
        \ "<CR>"

**Comment by 7belrhalmia** [comment] 2015-08-29 21:20
@Shougo  i think it's a problem with deoplete

**Comment by svanharmelen** [comment] 2015-08-29 21:25
@7belrhalmia thanks! That looks to be the same so I'll wait for some feedback from @Shougo on this one...

**Comment by 7belrhalmia** [comment] 2015-08-29 21:41
@svanharmelen  mapping < cr> will cause a problem with completing fields

**Comment by 7belrhalmia** [comment] 2015-08-29 21:49
@Shougo  why before neosnippet create an autosnippet , neosnippet run clear all previous markers like that we can avoid this problem

**Comment by svanharmelen** [comment] 2015-08-29 21:52
Yeah I saw that, but don't think it will be a problem for me (with fhe way I work). But maybe after I managed to make it work, I'll find out otherwise :wink:

**Comment by svanharmelen** [comment] 2015-08-29 21:57
Hmm... So you're saying that even if you visited the last marker, it will still exist? I thought that is you visited it, it will be remove/replaced. So you only have this problem is you do not visit all the markers. But seems I'm wrong then. Your suggestion to clear previous markers before adding a nee one sounds like a possible solution for this...

**Comment by Shougo** [comment] 2015-08-30 09:14
> If I change only <CR> for L, it works correctly using L... So what am I doing wrong? @Shougo could you confirm this isn't a deoplete specific problem? As the exact same thing seems to work with neocomplete.

@svanharmelen I cannot reproduce the problem.
Please create minimal .nvimrc.

**Comment by Shougo** [comment] 2015-08-30 09:18
> @Shougo why before neosnippet create an autosnippet , neosnippet run clear all previous markers like that we can avoid this problem

Please update neosnippet.  I fixed it in latest version.

**Comment by svanharmelen** [comment] 2015-08-30 09:28
@Shougo cool, thanks!

And as for the key mappings... Seems I also cannot reproduce it with a minimal .nvimrc. So I should be able to find and fix this myself I guess.

Thanks pushing me in the right direction!

**Comment by svanharmelen** [comment] 2015-08-30 09:47
It seems the problem is coming from this plugin: jiangmiao/auto-pairs

When I have that enabled it gives me the bad result. When I disable it, all is good again...

**Comment by 7belrhalmia** [comment] 2015-08-30 16:42
@Shougo  there is one other big problem with this function ,  

look at the exemple :  the function handleFunc hase only two paramettre (but also include another function ) so it dosen't ansert only two but tree paramettre see in the example

![gifrecord_2015-08-30_173634](https://cloud.githubusercontent.com/assets/13202562/9568320/306b582e-4f3e-11e5-8fab-77ded4cf8adc.gif)

**Comment by Shougo** [comment] 2015-08-31 19:29
@7belrhalmia This is not neosnippet issues.   Please create new issue in neosnippet.

**Comment by DerWeh** [comment] 2016-11-07 22:21
Can anyone explain how I have to setup `neocomplete`/`neosnippet`/ `neosnippet-snippets` to make this work? What are the settings I need?

**Comment by Shougo** [comment] 2016-11-07 22:25
> Can anyone explain how I have to setup neocomplete/neosnippet/ neosnippet-snippets to make this work? What are the settings I need?

You should read the plugin documentations at first.
