### ISSUE TITLE
Getting "Error occurred in source's gather_candidates()!" inside cabal sandbox

### ISSUE THREAD

**Issue by Ivanknmk** [Shougo/neocomplete.vim#490] opened 2015-10-26 07:47 UTC
I'm getting this error whenever I'm opening a file in a cabal sandbox (if i open a different file not in a cabal project), everything works perfect.

Running vim v7.4.898 with lua
and latest version of neocomplete

**Comment by Shougo** [comment] 2015-10-26 13:09
Please read the issue template.

https://github.com/Shougo/neocomplete.vim/issues/236

I cannot reproduce the problem.

Important:  Please upload the full error log.
You can use `:redir` command or upload the screenshot.

**Comment by Ivanknmk** [comment] 2015-10-26 15:43
## Expected

Opening a file not in a cabal sandbox, works fine:

![screen shot 2015-10-26 at 8 06 06 am](https://cloud.githubusercontent.com/assets/1672248/10732690/7735e11a-7bb8-11e5-92c7-5ca6319833e4.png)


## Environment Information
 * OS: Yosemite (10.10.5)
 * Vim version: 7.4.898

## Minimal vimrc less than 50 lines

https://gist.github.com/Ivanknmk/dd41fa91f3fd99030fa7

## Reproducible ways from Vim starting

 1.<leader>f to open unite
 2. Open a haskell file (.hs) inside a cabal sandbox (again, if I open a different file, no errors)
 3. Start typing and 

## Screen shot (if possible)

Typing the first letter: 
![screen shot 2015-10-26 at 7 56 08 am](https://cloud.githubusercontent.com/assets/1672248/10732556/dbe2714c-7bb7-11e5-9c35-8a92a9b0ad3c.png)

More letters:
![screen shot 2015-10-26 at 7 56 26 am](https://cloud.githubusercontent.com/assets/1672248/10732557/dbe35b98-7bb7-11e5-8a8e-e022b83a2fe8.png)

And closing vim:
![screen shot 2015-10-26 at 8 12 08 am](https://cloud.githubusercontent.com/assets/1672248/10732852/50485c30-7bb9-11e5-8153-f374a26cae8e.png)


## Full error log

```
"main.hs" 5L, 83C
[neocomplete] function neocomplete#handler#_do_auto_complete[43]..neocomplete#complete#_get_results[10]..neocomplete#complete#_set_results_pos[16]..neocomplete#helper#c
all_hook[4]..115[1]..necoghc#boot[6]..<SNR>186_ghc_mod_caching_browse[7]..<SNR>186_ghc_mod, line 7
[neocomplete] Vim(lcd):E344: Can't find directory "/Users/igarcia/haskell/workspace/gotfeedback/dist/setup-config: hGetContents: invalid argument (invalid byte sequence
)" in cdpath
[neocomplete] Error occurred in calling hook "on_init"!
[neocomplete] Source name is ghc
[neocomplete] function neocomplete#handler#_do_auto_complete[43]..neocomplete#complete#_get_results[23]..neocomplete#complete#_set_results_words[26]..118[12]..necoghc#g
et_complete_words[88]..necoghc#browse[2]..<SNR>186_ghc_mod_caching_browse[7]..<SNR>186_ghc_mod, line 7
[neocomplete] Vim(lcd):E344: Can't find directory "/Users/igarcia/haskell/workspace/gotfeedback/dist/setup-config: hGetContents: invalid argument (invalid byte sequence
)" in cdpath
[neocomplete] Source name is ghc
[neocomplete] Error occurred in source's gather_candidates()!
[neocomplete] function neocomplete#handler#_do_auto_complete[43]..neocomplete#complete#_get_results[23]..neocomplete#complete#_set_results_words[26]..118[12]..necoghc#g
et_complete_words[88]..necoghc#browse[2]..<SNR>186_ghc_mod_caching_browse[7]..<SNR>186_ghc_mod, line 7
[neocomplete] Vim(lcd):E344: Can't find directory "/Users/igarcia/haskell/workspace/gotfeedback/dist/setup-config: hGetContents: invalid argument (invalid byte sequence
)" in cdpath
[neocomplete] Source name is ghc
[neocomplete] Error occurred in source's gather_candidates()!
[neocomplete] function neocomplete#handler#_do_auto_complete[43]..neocomplete#complete#_get_results[23]..neocomplete#complete#_set_results_words[26]..118[12]..necoghc#g
et_complete_words[88]..necoghc#browse[2]..<SNR>186_ghc_mod_caching_browse[7]..<SNR>186_ghc_mod, line 7
[neocomplete] Vim(lcd):E344: Can't find directory "/Users/igarcia/haskell/workspace/gotfeedback/dist/setup-config: hGetContents: invalid argument (invalid byte sequence
)" in cdpath
[neocomplete] Source name is ghc
[neocomplete] Error occurred in source's gather_candidates()!
```

**Comment by Shougo** [comment] 2015-10-28 13:50
> And closing vim:

The error is fixed.  Please update neco-ghc.

> I'm getting this error whenever I'm opening a file in a cabal sandbox (if i open a different file not in a cabal project), everything works perfect.

https://github.com/kazu-yamamoto/ghc-mod/issues/429

It is ghc-mod problem.  You should update ghc-mod to latest version.
It is not neco-ghc or neocomplete problem.  Closing.

**Closed by Shougo** 2015-10-28 13:50 UTC

**Comment by Ivanknmk** [comment] 2015-10-28 15:55
Thank you very much for the detailed explanation @Shougo
